#!/bin/bash
# Dotfiles installation script

print_usage_and_exit() {
   echo "Usage:
        dotfiles --help | <config_type (minimal/full)> [--check] [--install]
    "
    exit 1
}

# Parse arguments
if [[ -z "$1" ]] || ( [[ "$1" != "minimal" ]] && [[ "$1" != "full" ]] ) || ( [[ "$1" -eq "--help" ]] && [[ "$1" -eq "-h" ]] ); then
    print_usage_and_exit
else
    CONFIG_TYPE="$1"
    shift # pass minimal/full
fi

INSTALL_FLAG=0
CHECK_FLAG=1

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            shift
            echo "Showing help.\n"
            print_usage_and_exit 
            ;;
        -c|--check)
            CHECK_FLAG=1
            shift # past argument
            ;;
        -i|--install)
            INSTALL_FLAG=1
            shift # past argument
            ;;
        -*|--*)
            echo "Unknown option $1."
            print_usage_and_exit
            ;;
        *)
            echo "Unknown positional argument $1"
            print_usage_and_exit
            ;;
    esac
done

REQUIREMENTS_MINIMAL=""
REQUIREMENTS_FULL=""


#if [[ $INSTALL_FLAG -eq 1 ]]; then
#    if ( [[ $INSTALL_FLAG -eq 1 ]] && ( [[ $INSTALL_TYPE != "full" ]] && [[ $INSTALL_TYPE != "minimal" ]] )); then
#fi

#echo "FILE EXTENSION  = ${EXTENSION}"
#echo "SEARCH PATH     = ${SEARCHPATH}"
#echo "DEFAULT         = ${DEFAULT}"
#echo "Number files in ${SEARCHPATH} with ${EXTENSION} extension:" $(ls -1 "${SEARCHPATH}"/*."${EXTENSION}" | wc -l)

